CREATE TABLE CLIENTE(
ID_CLIENTE NUMBER (11) NOT NULL,
NOME VARCHAR(100) NOT NULL,
PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE LOGIN(
ID_LOGIN NUMBER (11) NOT NULL,
ID_CLIENTE NUMBER (11) NOT NULL,
LOGIN VARCHAR(50) UNIQUE NOT NULL,
SENHA NUMBER(38) NOT NULL,
CONSTRAINT PK_LOGIN_ID_LOGIN PRIMARY KEY (ID_LOGIN, ID_CLIENTE),
CONSTRAINT FK_CLIENTE_ID_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
);

CREATE TABLE CONTATO(
ID_CONTATO NUMBER (11) NOT NULL,
ID_CLIENTE NUMBER (11) NOT NULL,
TELEFONE NUMBER (12) NOT NULL,
DESCRICAO VARCHAR (100) NOT NULL,
CONSTRAINT PK_CONTATO_ID_CONTATO PRIMARY KEY (ID_CONTATO, ID_CLIENTE),
CONSTRAINT FK_CONTATO_ID_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
);

CREATE TABLE ENDERECO(
ID_ENDERECO NUMBER (11) NOT NULL,
ID_CLIENTE NUMBER (11) NOT NULL,
CEP CHAR (9) NOT NULL,
LOGRADOURO VARCHAR (255) NOT NULL,
CIDADE VARCHAR (100) NOT NULL,
BAIRRO VARCHAR (100) NOT NULL,
NUMERO NUMBER (8) NOT NULL,
COMPLEMENTO VARCHAR (100) NOT NULL,
CONSTRAINT PK_ENDERECO_ID_ENDERECO PRIMARY KEY (ID_ENDERECO, ID_CLIENTE),
CONSTRAINT FK_ENDERECO_ID_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
);

CREATE TABLE ANIMAL(
ID_ANIMAL NUMBER (11) NOT NULL,
ID_CLIENTE NUMBER (11) NOT NULL,
NOME VARCHAR (50) NOT NULL,
RACA VARCHAR (50) NOT NULL,
PELAGEM NUMBER(1) NOT NULL,
PORTE NUMBER(1) NOT NULL,
VALOR_CONTRATO NUMBER (10) NOT NULL,
QUANTIDADE_CONTRATOS NUMBER (10) NOT NULL,
CONSTRAINT PK_ANIMAL_ID_ANIMAL PRIMARY KEY (ID_ANIMAL, ID_CLIENTE),
CONSTRAINT FK_ANIMAL_ID_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
);

CREATE TABLE CACHORRO(
ID_CACHORRO NUMBER (11) NOT NULL,
ID_ANIMAL NUMBER (11) NOT NULL,
ID_CLIENTE NUMBER (11) NOT NULL,
PODE_ROER_OSSO CHAR (1) NOT NULL,
CONSTRAINT PK_CACHORRO_ID_CACHORRO PRIMARY KEY (ID_CACHORRO, ID_ANIMAL),
CONSTRAINT FK_CACHORRO_ID_ANIMAL FOREIGN KEY (ID_ANIMAL, ID_CLIENTE) REFERENCES ANIMAL (ID_ANIMAL, ID_CLIENTE)
);

CREATE TABLE GATO(
ID_GATO NUMBER (11) NOT NULL,
ID_ANIMAL NUMBER (11) NOT NULL,
ID_CLIENTE NUMBER (11) NOT NULL,
PODE_BRINCAR_COM_LA CHAR (1) NOT NULL,
CONSTRAINT PK_GATO_ID_GATO PRIMARY KEY (ID_GATO, ID_ANIMAL),
CONSTRAINT FK_GATO_ID_ANIMAL FOREIGN KEY (ID_ANIMAL, ID_CLIENTE) REFERENCES ANIMAL (ID_ANIMAL, ID_CLIENTE)
);

CREATE SEQUENCE SEQ_ID_CLIENTE
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_ID_LOGIN
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_ID_CONTATO 
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_ID_ENDERECO  
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_ID_ANIMAL  
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_ID_CACHORRO  
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_ID_GATO  
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

----------

INSERT INTO VEM_SER.CLIENTE (ID_CLIENTE, NOME)
VALUES (SEQ_ID_CLIENTE.nextval, 'Eduardo Miranda');

INSERT INTO VEM_SER.LOGIN (ID_LOGIN, ID_CLIENTE, LOGIN, SENHA)
VALUES (SEQ_ID_LOGIN.nextval, 1, 'miranda', 123456);

INSERT INTO VEM_SER.CONTATO (ID_CONTATO, ID_CLIENTE, TELEFONE, DESCRICAO)
VALUES (SEQ_ID_CONTATO.nextval, 1, 55999998888, 'celular');

INSERT INTO VEM_SER.ENDERECO (ID_ENDERECO, ID_CLIENTE, CEP, LOGRADOURO, CIDADE, BAIRRO, NUMERO, COMPLEMENTO)
VALUES (SEQ_ID_ENDERECO.nextval, 1, 888888543, 'Rua pokemon', 'Pallet', 'Vila do Raio', 151, 'Casa');

INSERT INTO VEM_SER.ANIMAL (ID_ANIMAL, ID_CLIENTE, NOME, RACA, PELAGEM, PORTE, VALOR_CONTRATO, QUANTIDADE_CONTRATOS)
VALUES (SEQ_ID_ANIMAL.nextval, 1, 'pikachu', 'corgi', 7, 1, 35, 1);

INSERT INTO VEM_SER.CACHORRO (ID_CACHORRO, ID_ANIMAL, ID_CLIENTE, PODE_ROER_OSSO)
VALUES (SEQ_ID_CACHORRO.nextval, 1, 1, 1);

-----------

INSERT INTO VEM_SER.CLIENTE (ID_CLIENTE, NOME)
VALUES (SEQ_ID_CLIENTE.nextval, 'Gabriel Luppi');

INSERT INTO VEM_SER.LOGIN (ID_LOGIN, ID_CLIENTE, LOGIN, SENHA)
VALUES (SEQ_ID_LOGIN.nextval, 2, 'luppi', 1234567);

INSERT INTO VEM_SER.CONTATO (ID_CONTATO, ID_CLIENTE, TELEFONE, DESCRICAO)
VALUES (SEQ_ID_CONTATO.nextval, 2, 55888779999, 'celular');

INSERT INTO VEM_SER.ENDERECO (ID_ENDERECO, ID_CLIENTE, CEP, LOGRADOURO, CIDADE, BAIRRO, NUMERO, COMPLEMENTO)
VALUES (SEQ_ID_ENDERECO.nextval, 2, 177775543, 'Rua Genshin', 'Summers rift', 'Aram', 521, 'Ao lado da torre do mid');

INSERT INTO VEM_SER.ANIMAL (ID_ANIMAL, ID_CLIENTE, NOME, RACA, PELAGEM, PORTE, VALOR_CONTRATO, QUANTIDADE_CONTRATOS)
VALUES (SEQ_ID_ANIMAL.nextval, 2, 'Riolu', 'Pastor Alemao', 8, 9, 120, 3);

INSERT INTO VEM_SER.CACHORRO (ID_CACHORRO, ID_ANIMAL, ID_CLIENTE, PODE_ROER_OSSO)
VALUES (SEQ_ID_CACHORRO.nextval, 2, 2, 0);

INSERT INTO VEM_SER.ANIMAL (ID_ANIMAL, ID_CLIENTE, NOME, RACA, PELAGEM, PORTE, VALOR_CONTRATO, QUANTIDADE_CONTRATOS)
VALUES (SEQ_ID_ANIMAL.nextval, 1, 'Eliza', 'Persa', 0, 5, 600, 5);

INSERT INTO VEM_SER.GATO (ID_GATO, ID_ANIMAL, ID_CLIENTE, PODE_BRINCAR_COM_LA)
VALUES (SEQ_ID_GATO.nextval, 3, 1, 1);

